// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeechTherapist.Data;

#nullable disable

namespace SpeechTherapist.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251124094136_one-to-many")]
    partial class onetomany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Appointments", b =>
                {
                    b.Property<int>("AppointmentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentCode"));

                    b.Property<DateTime>("DateAndHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientCode")
                        .HasColumnType("int");

                    b.Property<int>("PatientsPatientCode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentCode")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentsTreatmentCode")
                        .HasColumnType("int");

                    b.HasKey("AppointmentCode");

                    b.HasIndex("PatientsPatientCode");

                    b.HasIndex("TreatmentsTreatmentCode");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Patients", b =>
                {
                    b.Property<int>("PatientCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientCode"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientCode");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Treatments", b =>
                {
                    b.Property<int>("TreatmentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentCode"));

                    b.Property<float>("DurationMinutes")
                        .HasColumnType("real");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TreatmentCode");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Appointments", b =>
                {
                    b.HasOne("SpeechTherapist.Core.Entities.Patients", "Patients")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientsPatientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeechTherapist.Core.Entities.Treatments", "Treatments")
                        .WithMany("Appointments")
                        .HasForeignKey("TreatmentsTreatmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patients");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Patients", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Treatments", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
