// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeechTherapist.Data;

#nullable disable

namespace SpeechTherapist.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Appointments", b =>
                {
                    b.Property<int>("AppointmentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentCode"));

                    b.Property<DateTime>("DateAndHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientCode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentCode")
                        .HasColumnType("int");

                    b.HasKey("AppointmentCode");

                    b.HasIndex("PatientCode");

                    b.HasIndex("TreatmentCode");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Patients", b =>
                {
                    b.Property<int>("PatientCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientCode"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpeechTerapistSpeechTherapistCode")
                        .HasColumnType("int");

                    b.Property<int>("SpeechTherapistCode")
                        .HasColumnType("int");

                    b.Property<int>("UserCode")
                        .HasColumnType("int");

                    b.HasKey("PatientCode");

                    b.HasIndex("SpeechTerapistSpeechTherapistCode");

                    b.HasIndex("SpeechTherapistCode");

                    b.HasIndex("UserCode");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Report", b =>
                {
                    b.Property<int>("ReportCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportCode"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleDocUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApprovedByTherapist")
                        .HasColumnType("bit");

                    b.Property<int>("PatientCode")
                        .HasColumnType("int");

                    b.Property<int>("SpeechTherapistCode")
                        .HasColumnType("int");

                    b.HasKey("ReportCode");

                    b.HasIndex("PatientCode");

                    b.HasIndex("SpeechTherapistCode");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.SpeechTerapist", b =>
                {
                    b.Property<int>("SpeechTherapistCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeechTherapistCode"));

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCode")
                        .HasColumnType("int");

                    b.HasKey("SpeechTherapistCode");

                    b.HasIndex("UserCode");

                    b.ToTable("speechTerapists");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Treatments", b =>
                {
                    b.Property<int>("TreatmentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentCode"));

                    b.Property<float>("DurationMinutes")
                        .HasColumnType("real");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TreatmentCode");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Users", b =>
                {
                    b.Property<int>("UserCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCode"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserCode");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Appointments", b =>
                {
                    b.HasOne("SpeechTherapist.Core.Entities.Patients", "Patients")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeechTherapist.Core.Entities.Treatments", "Treatments")
                        .WithMany("Appointments")
                        .HasForeignKey("TreatmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patients");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Patients", b =>
                {
                    b.HasOne("SpeechTherapist.Core.Entities.SpeechTerapist", null)
                        .WithMany("Patients")
                        .HasForeignKey("SpeechTerapistSpeechTherapistCode");

                    b.HasOne("SpeechTherapist.Core.Entities.SpeechTerapist", "speechTherapist")
                        .WithMany()
                        .HasForeignKey("SpeechTherapistCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpeechTherapist.Core.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("speechTherapist");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Report", b =>
                {
                    b.HasOne("SpeechTherapist.Core.Entities.Patients", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpeechTherapist.Core.Entities.SpeechTerapist", "SpeechTherapist")
                        .WithMany()
                        .HasForeignKey("SpeechTherapistCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SpeechTherapist");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.SpeechTerapist", b =>
                {
                    b.HasOne("SpeechTherapist.Core.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Patients", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.SpeechTerapist", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SpeechTherapist.Core.Entities.Treatments", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
